Repository gtaEPIC/COMP229-Deskify, pull requests merged in 2023-11, with the labels that each got.

#1 Project README
  README.md
Labels: enhancement

#2 Created a base Express EJS Server
  app.js
  bin/www
  package-lock.json
  package.json
  public/stylesheets/style.css
  routes/index.js
  routes/users.js
  views/error.ejs
  views/index.ejs
Labels: REQUIRED

#18 Updating Folder Structure.
  config/app.js
  config/config.js
  config/db.js
  server.js
Labels: enhancement

#20 Base Ticket system
  README.md
  config/app.js
  config/config.js
  config/db.js
  controllers/ticketController.js
  models/ticket.js
  package-lock.json
  package.json
  routes/ticketRoute.js
  server.js
Labels: REQUIRED

#21 Ticket iteration
  controllers/ticketController.js
  models/ticket.js
Labels: REQUIRED

#22 Emergency: Quick bug fix since it was missed in the pull request
  controllers/ticketController.js
Labels: bug, REQUIRED

#24 Escape
  controllers/ticketController.js
  models/ticket.js
Labels: REQUIRED

#26 User registration
  config/app.js
  controllers/userResgistration.js
  models/userResgistration.js
  routes/userRegistration.js
  routes/users.js
  views/index.ejs
  views/ticketEdit.ejs
Labels: REQUIRED

#29 Security Update
  config/app.js
  controllers/ticketController.js
  models/ticket.js
  routes/ticketRoute.js
  views/ticketView.ejs
Labels: REQUIRED
